### ISSUE TITLE
1.21 Duping

### ISSUE THREAD

**Issue by KyrVorga** [percyqaz/UltimateInventory#13]
Heya, not sure if you're still working on this plugin, but I'm using it on a 1.21 Purpur server, and there's a duping bug.

The steps to reproduce are:
- Have a shulker with a block in it.
- Place it on the ground.
- Pick it up.
- Open it in Inventory, and take the block.
- Place shulker.
- Open shulker and take block again.

I know you haven't officially supported 1.21, but other than this, it works flawlessly.

**Comment by percyqaz** [comment]
Thanks for reporting, is there any chance you can get a screen recording of it?

**Comment by percyqaz** [comment]
Hi again, I am prodding for more info since trying to replicate this has turned out nothing

On the latest Purpur builds for both 1.21 and 1.21.1 + just Ultimate Inventory I can't trigger any duplication glitches, similarly on my private Minecraft server nobody has experienced issues after upgrading to 1.21.1

I will assume for now that this is a compatibility bug rather than something broken since 1.20

**Comment by KyrVorga** [comment]
Apologies for not getting back to you on this. It ended up being a config issue with AuraSkills. 

For anyone who somehow stumbles into this issue, disable `auto_convert_from_legacy`.
